// <auto-generated />
using CoracaoEvangelho.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CoracaoEvangelho.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405000000_AdicionaCamposCursoDetalheEDepoimentos")]
    partial class AdicionaCamposCursoDetalheEDepoimentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Modelo gerenciado pelo AppDbContextModelSnapshot.cs
        }
    }
}
